repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: end-of-file-fixer #Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace #Trims trailing whitespace.
      - id: check-added-large-files # Prevent giant files from being committed.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff-format
        args: [--check]
        types_or: [python, pyi, jupyter]
